/*
 * TeleStax, Open Source Cloud Communications
 * Copyright 2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

package org.restcomm.connect.rvd.model;

import java.util.List;

/**
 * Storage entity for a project template
 *
 * Fields:
 *
 * id - a random identifier generated by RVD when the template is created
 * name - A friendly_name for this template
 * description - (optional) a longer text for the template no more than 250 characters. In the future we may store html code in this field. For now, no special html formatting will take place
 * imageUrl - (optional) A custom image that will part of the template resources. If not supplied the system will use a default in the UI. Relative links path (not starting with '/' of 'http') is pl aced right under the path that gets the template itself (?)
 * infoUrl - (optional) A link with further information on this application template. The information will not be hosted by the system. Only absolute urls supported.
 *
 * @author otsakir@gmail.com - Orestis Tsakiridis
 */
public class ProjectTemplate {
    String id;
    String name;
    String description;
    String imageUrl;
    String infoUrl;
    List<String> tags;

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public String getInfoUrl() {
        return infoUrl;
    }

    public List<String> getTags() {
        return tags;
    }
}
